ALTER TABLE store.item ALTER COLUMN id SET DEFAULT nextval('store.item_sequence');

INSERT INTO store.item (vin, dealer_id)
VALUES ('VYJIMWKHLLIUSWQRR', 'D345GFG'),
       ('AVBNZMOMKPDLELCJC', 'D678DFG'),
       ('VRMZJDUMWTDDASAAK', 'D903DDF'),
       ('ASLLDOAPMWRORWOCO', 'D567YTR'),
       ('GJHIZGGZVYXRZDVRC', 'D345GFG'),
       ('PLZUZWYJUHUNGTUDD', 'D678DFG'),
       ('MKETIBHSBXNJPGLTD', 'D903DDF'),
       ('QKFFPAAVGYGJXHBTM', 'D567YTR'),
       ('WMRZVXCCJYFZFRYHY', 'D345GFG'),
       ('TFCMNMXBCULOUVEKC', 'D678DFG'),
       ('JNVKGTCPLUJABCEXH', 'D903DDF'),
       ('XXSNNIOZROSVJZKFD', 'D567YTR'),
       ('ZUZZEJUOTDZOBMPHT', 'D345GFG'),
       ('XXQCEVCJXRKMFYYGF', 'D678DFG'),
       ('NNLULJSNQQFBTVEJG', 'D903DDF'),
       ('TPWGSZNTGGKAVZRTX', 'D567YTR'),
       ('PZLXJDTOMUIFZJWSD', 'D345GFG'),
       ('OJWTVEDKWJUENMTIW', 'D678DFG'),
       ('FJGJTHSGFKJHJKRTS', 'D903DDF'),
       ('LKIOJHYJHYTFRHJDF', 'D567YTR');
